name: LeetCode Automation

on:
  push:
    branches:
      - main

jobs:
  automate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check repository
        run: |
          echo "LeetCode repository updated!"
          echo "Automation is working."
          ls -R
